### ISSUE TITLE
Allele type warning to fix automatically

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#473]
There are lots of warnings like this from the Canto load:
    warning in 073951bf43ce4011: allele_type for new allele "cdc19-D8(other)" does not match the existing allele with the same name "cdc19-D8(partial_amino_acid_deletion)" (from session 073951bf43ce4011)

Can we assume that when one allele type is "other" that the two alleles are the same?

**Comment by mah11** [comment]
I fixed a bunch of these yesterday (after the 06-Aug load started), and all of the ones I did were indeed the same allele description; just the type got botched somehow. Don't know how many are left now, but might be worth an auto-fix for future-proofing.

**Comment by kimrutherford** [comment]
OK, this doesn't sound so urgent so I'll bump this to the next release.

**Comment by mah11** [comment]
One odd thing now: the canto log for the latest build now (log.2015-08-07-02-51-46.curation-tool-data-load-output) still has warnings for the "other" alleles that I fixed. I know I would've missed the 06-Aug load, but am surprised the fixes didn't make it into the 07-Aug build. Am I just being impatient?

**Comment by kimrutherford** [comment]
> Am I just being impatient?

Hopefully it's just a timing problem.  Another load is running and will be done in 4-ish hours.  If it's not fixed then let me know and I'll dig into it.

**Comment by mah11** [comment]
Hmm. They are still there in log.2015-08-09-07-00-30.curation-tool-data-load-output

example:
warning in 073951bf43ce4011: allele_type for new allele "cdc19-D8(other)" does not match the existing allele with the same name "cdc19-D8(partial_amino_acid_deletion)" (from session 073951bf43ce4011)

... and all the other warnings from the same session, as well as a few others

**Comment by kimrutherford** [comment]
Sorry about that.  I've had a look now.  You had fixed the warning (by deleting the alleles by the look of it).  They are still hanging around in the database but not visible from the interface.

It's a problem that I sort-of caused on purpose.  Currently when you edit an allele or remove a genotype, it doesn't clean up the alleles that are now unused.  Deleting from database always makes me nervous so I thought I'd leave that problem for a while until everything was working.  I was hoping that wouldn't cause problems but it is causing warnings.

Those invisible, deleted alleles shouldn't cause Mark trouble because they don't have annotation attached.

I'll remove those unused alleles and fix the Canto code before the next release.

**Comment by mah11** [comment]
OK. Thanks for the explanation. I was starting to wonder if I'd really fixed what I thought I had .. if it weren't for that it wouldn't have been a problem.

**Comment by kimrutherford** [comment]
> I'll remove those unused alleles and fix the Canto code before the next release.

The Canto database is now fixed and I'm running a new load.

**Comment by kimrutherford** [comment]
I think this is fixed now.  Please re-open if there is still a problem.
